// This file is auto-generated by scripts/route-matchers.ts
// Do not edit manually - run "bun scripts/route-matchers.ts" to regenerate

import { type NextRequest } from "next/server";

export function createRouteMatcher(patterns: string[]) {
  const regexes = patterns.map((pattern) => new RegExp(pattern));

  return (request: NextRequest) => {
    const { pathname } = request.nextUrl;
    return regexes.some((regex) => regex.test(pathname));
  };
}

export function isStaticRoute(pathname: string): boolean {
  const cleanPath = pathname.startsWith("/") ? pathname.substring(1) : pathname;
  const firstSegment = cleanPath.split("/")[0];
  if (!firstSegment) return false;
  return (STATIC_ROUTES as readonly string[]).includes(firstSegment) || (STATIC_ROUTES as readonly string[]).includes(cleanPath);
}

/**
 * All static routes extracted from /src/app directory
 */
export const STATIC_ROUTES = [
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/vercel/flags",
  "api/cron/transfers",
  "api/og/imagegen",
  "api/uploadthing",
  "create",
  "edit",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * All public asset paths from /public directory
 */
export const PUBLIC_PATHS = [
  "/favicon.ico",
  "/logo.png",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/placeholder.svg"
] as const;

/**
 * All paths combined (static routes + public assets)
 */
export const ALL_PATHS = [
  "/favicon.ico",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/logo.png",
  "/placeholder.svg",
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/vercel/flags",
  "api/cron/transfers",
  "api/og/imagegen",
  "api/uploadthing",
  "create",
  "edit",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * First segments from all paths - used for intelligent route matching
 */
export const FIRST_SEGMENTS = [
  "api",
  "create",
  "edit",
  "internal",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * Bypass routes that should instantly pass through middleware
 */
export const BYPASS_ROUTES = [
  "/__nextjs_original-stack-frame",
  "/_next",
  "/_next/*",
  "/_vercel",
  "/_vercel/*",
  "/api/2well2know",
  "/api/2well2know/*",
  "/api/cron",
  "/api/cron/*",
  "/api/mcp",
  "/api/mcp/*",
  "/api/og",
  "/api/og/*",
  "/api/trpc",
  "/api/trpc/*",
  "/api/uploadthing",
  "/api/uploadthing/*",
  "/favicon.ico",
  "/health",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/ingest/*",
  "/ingest/decide",
  "/ingest/static/*",
  "/logo.png",
  "/manifest.json",
  "/ping",
  "/placeholder.svg",
  "/robots.txt",
  "/sitemap.xml",
  "/status"
] as const;

/**
 * All route information extracted from /src/app directory
 */
export const ALL_ROUTES = [
  {
    path: "/privacy",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["privacy"]
  },
  {
    path: "/terms",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["terms"]
  },
  {
    path: "/api/cron/transfers",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "cron", "transfers"]
  },
  {
    path: "/api/og/imagegen",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "og", "imagegen"]
  },
  {
    path: "/api/trpc/[trpc]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "trpc", "[trpc]"]
  },
  {
    path: "/api/uploadthing",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "uploadthing"]
  },
  {
    path: "/api/2well2know/vercel/flags",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "vercel", "flags"]
  },
  {
    path: "/api/2well2know/oauth-authorization-server",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "oauth-authorization-server"]
  },
  {
    path: "/api/auth/[...all]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "auth", "[...all]"]
  },
  {
    path: "/api/mcp/[transport]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "mcp", "[transport]"]
  },
  {
    path: "/api/internal/org-check/[orgSlug]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "internal", "org-check", "[orgSlug]"]
  },
  {
    path: "/create",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["create"]
  },
  {
    path: "/edit/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["edit", "[shortname]"]
  },
  {
    path: "/manage",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["manage"]
  },
  {
    path: "/pricing",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["pricing"]
  },
  {
    path: "/profile/[[...user-profile]]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["profile", "[[...user-profile]]"]
  },
  {
    path: "/sign-in/[[...sign-in]]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["sign-in", "[[...sign-in]]"]
  },
  {
    path: "/sign-up/[[...sign-up]]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["sign-up", "[[...sign-up]]"]
  },
  {
    path: "/waitlist",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["waitlist"]
  },
  {
    path: "/",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: []
  },
  {
    path: "/",
    isPage: false,
    isLayout: true,
    isApi: false,
    isDynamic: false,
    segments: []
  },
  {
    path: "/internal/hero/B2B",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "hero", "B2B"]
  },
  {
    path: "/internal/hero/B2C",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "hero", "B2C"]
  },
  {
    path: "/internal/home/org/[orgSlug]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "home", "org", "[orgSlug]"]
  },
  {
    path: "/internal/home/user",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "home", "user"]
  },
  {
    path: "/internal/profile/org/[orgSlug]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "profile", "org", "[orgSlug]"]
  },
  {
    path: "/internal/profile/user/[username]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "profile", "user", "[username]"]
  },
  {
    path: "/internal/view/free/[username]/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "free", "[username]", "[shortname]"]
  },
  {
    path: "/internal/view/org/[orgSlug]/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "org", "[orgSlug]", "[shortname]"]
  },
  {
    path: "/internal/view/pro/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "pro", "[shortname]"]
  },
  {
    path: "/internal",
    isPage: false,
    isLayout: true,
    isApi: false,
    isDynamic: false,
    segments: ["internal"]
  }
] as const;

/**
 * Combined forbidden names: static routes + template forbidden names
 */
export const forbiddenNames = [
  "admin",
  "anonymous",
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/vercel/flags",
  "api/cron/transfers",
  "api/og/imagegen",
  "api/uploadthing",
  "app",
  "assets",
  "auth",
  "blog",
  "cdn",
  "cert",
  "create",
  "deck",
  "decks",
  "demo",
  "docs",
  "edit",
  "email",
  "example",
  "ftp",
  "guest",
  "help",
  "home",
  "index",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "key",
  "login",
  "logout",
  "mail",
  "manage",
  "mobile",
  "null",
  "oauth",
  "presentation",
  "presentations",
  "pricing",
  "privacy",
  "private",
  "profile",
  "public",
  "register",
  "root",
  "secret",
  "secure",
  "shop",
  "sign-in",
  "sign-up",
  "signin",
  "signup",
  "site",
  "slide",
  "slides",
  "ssl",
  "sso",
  "static",
  "store",
  "support",
  "system",
  "terms",
  "test",
  "undefined",
  "user",
  "waitlist",
  "web",
  "www"
];

/**
 * Route matchers for common route patterns
 */
export const isAuth = createRouteMatcher([
  "/sign-in(.*)",
  "/sign-up(.*)", 
  "/pricing(.*)",
  "/waitlist(.*)",
  "/profile(.*)",
]);

export const isManagement = createRouteMatcher([
  "/manage(.*)",
  "/edit/(.*)", 
  "/create(.*)",
]);

export const isLegal = createRouteMatcher(["/terms(.*)", "/privacy(.*)"]);

export const isOrgManagement = createRouteMatcher([
  "/org/create(.*)",
  "/org/settings(.*)",
  "/profile/select(.*)",
]);

/**
 * Bypass matcher - instantly passes through middleware
 */
export const isBypass = createRouteMatcher(BYPASS_ROUTES.map(route => 
  route.includes('*') ? route.replace('*', '(.*)') : route
));

/**
 * Pro presentation matcher - matches /!shortname
 */
export const isProPresentation = createRouteMatcher(["/!([^/]+)"]);

/**
 * User profile matcher - matches single paths that are NOT in first segments
 */
export const isUserProfile = createRouteMatcher([
  "^/(?!" + FIRST_SEGMENTS.join("|") + ")([^/!]+)$"
]);

/**
 * Free presentation matcher - matches /username/shortname where username is NOT in first segments
 */
export const isFreePresentation = createRouteMatcher([
  "^/(?!" + FIRST_SEGMENTS.join("|") + ")([^/!]+)/([^/]+)$"
]);
export const isOrgRedirect = createRouteMatcher(["/org"]);
export const isSettingsRoute = createRouteMatcher(["/settings"]);
export const isManageRoute = createRouteMatcher(["/manage"]);
export const isRootRoute = createRouteMatcher(["^/$"]);

// Legacy matchers for backwards compatibility
export const isPaidPresentation = isProPresentation;
export const isFreeTier = isFreePresentation;

// Org-specific matcher (same as user profile for single paths)
export const isOrgPresentation = isUserProfile;
