// This file is auto-generated by scripts/route-matchers.ts
// Do not edit manually - run "bun scripts/route-matchers.ts" to regenerate

import { createRouteMatcher } from "~/lib/route-matchers";

export function isStaticRoute(pathname: string): boolean {
  const cleanPath = pathname.startsWith("/") ? pathname.substring(1) : pathname;
  const firstSegment = cleanPath.split("/")[0];
  if (!firstSegment) return false;
  return (STATIC_ROUTES as readonly string[]).includes(firstSegment) || (STATIC_ROUTES as readonly string[]).includes(cleanPath);
}

/**
 * All static routes extracted from /src/app directory
 */
export const STATIC_ROUTES = [
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/oauth-authorization-server.hide.",
  "api/2well2know/oauth-protected-resource",
  "api/2well2know/oauth-protected-resource.hide.",
  "api/2well2know/vercel/flags",
  "api/og/imagegen",
  "api/uploadthing",
  "create",
  "edit",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * All public asset paths from /public directory
 */
export const PUBLIC_PATHS = [
  "/favicon.ico",
  "/logo.png",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/placeholder.svg",
  "/unclipped-noblur.svg",
  "/unclipped.svg",
  "/wordmark.png"
] as const;

/**
 * All paths combined (static routes + public assets)
 */
export const ALL_PATHS = [
  "/favicon.ico",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/logo.png",
  "/placeholder.svg",
  "/unclipped-noblur.svg",
  "/unclipped.svg",
  "/wordmark.png",
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/oauth-authorization-server.hide.",
  "api/2well2know/oauth-protected-resource",
  "api/2well2know/oauth-protected-resource.hide.",
  "api/2well2know/vercel/flags",
  "api/og/imagegen",
  "api/uploadthing",
  "create",
  "edit",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * First segments from all paths - used for intelligent route matching
 */
export const FIRST_SEGMENTS = [
  "api",
  "create",
  "edit",
  "internal",
  "manage",
  "pricing",
  "privacy",
  "profile",
  "sign-in",
  "sign-up",
  "terms",
  "waitlist"
] as const;

/**
 * Bypass routes that should instantly pass through middleware
 */
export const BYPASS_ROUTES = [
  "/.well-known",
  "/.well-known/oauth-protected-resource/*",
  "/__nextjs_original-stack-frame",
  "/_next",
  "/_next/*",
  "/_vercel",
  "/_vercel/*",
  "/api/2well2know",
  "/api/2well2know/*",
  "/api/cron",
  "/api/cron/*",
  "/api/mcp",
  "/api/mcp/*",
  "/api/og",
  "/api/og/*",
  "/api/trpc",
  "/api/trpc/*",
  "/api/uploadthing",
  "/api/uploadthing/*",
  "/favicon.ico",
  "/health",
  "/img/handout.png",
  "/img/kahoot.png",
  "/img/list.png",
  "/img/mypr.png",
  "/img/og.png",
  "/img/pro-kahoot.png",
  "/img/share.png",
  "/img/usb.png",
  "/ingest/*",
  "/ingest/decide",
  "/ingest/static/*",
  "/logo.png",
  "/manifest.json",
  "/ping",
  "/placeholder.svg",
  "/robots.txt",
  "/sitemap.xml",
  "/status",
  "/unclipped-noblur.svg",
  "/unclipped.svg",
  "/wordmark.png"
] as const;

/**
 * All route information extracted from /src/app directory
 */
export const ALL_ROUTES = [
  {
    path: "/privacy",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["privacy"],
    category: "legal"
  },
  {
    path: "/terms",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["terms"],
    category: "legal"
  },
  {
    path: "/api/og/imagegen",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "og", "imagegen"],
    category: undefined
  },
  {
    path: "/api/uploadthing",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "uploadthing"],
    category: undefined
  },
  {
    path: "/api/2well2know/oauth-authorization-server.hide.",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "oauth-authorization-server.hide."],
    category: undefined
  },
  {
    path: "/api/2well2know/oauth-protected-resource.hide.",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "oauth-protected-resource.hide."],
    category: undefined
  },
  {
    path: "/api/2well2know/oauth-authorization-server",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "oauth-authorization-server"],
    category: undefined
  },
  {
    path: "/api/2well2know/oauth-protected-resource",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "oauth-protected-resource"],
    category: undefined
  },
  {
    path: "/api/2well2know/vercel/flags",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: false,
    segments: ["api", "2well2know", "vercel", "flags"],
    category: undefined
  },
  {
    path: "/api/mcp.hide./[[...transport]]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "mcp.hide.", "[[...transport]]"],
    category: undefined
  },
  {
    path: "/api/auth/[...all]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "auth", "[...all]"],
    category: undefined
  },
  {
    path: "/api/mcp/[[...transport]]",
    isPage: false,
    isLayout: false,
    isApi: true,
    isDynamic: true,
    segments: ["api", "mcp", "[[...transport]]"],
    category: undefined
  },
  {
    path: "/create",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["create"],
    category: undefined
  },
  {
    path: "/edit/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["edit", "[shortname]"],
    category: undefined
  },
  {
    path: "/manage",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["manage"],
    category: undefined
  },
  {
    path: "/pricing",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["pricing"],
    category: "auth"
  },
  {
    path: "/profile/[[...user-profile]]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["profile", "[[...user-profile]]"],
    category: "auth"
  },
  {
    path: "/sign-up/[[...sign-up]]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["sign-up", "[[...sign-up]]"],
    category: "auth"
  },
  {
    path: "/waitlist",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["waitlist"],
    category: "auth"
  },
  {
    path: "/sign-in",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["sign-in"],
    category: "auth"
  },
  {
    path: "/internal/hero/B2B",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "hero", "B2B"],
    category: undefined
  },
  {
    path: "/internal/hero/B2C",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "hero", "B2C"],
    category: undefined
  },
  {
    path: "/internal/home/org/[orgSlug]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "home", "org", "[orgSlug]"],
    category: undefined
  },
  {
    path: "/internal/home/user",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: ["internal", "home", "user"],
    category: undefined
  },
  {
    path: "/internal",
    isPage: false,
    isLayout: true,
    isApi: false,
    isDynamic: false,
    segments: ["internal"],
    category: undefined
  },
  {
    path: "/internal/profile/org/[orgSlug]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "profile", "org", "[orgSlug]"],
    category: undefined
  },
  {
    path: "/internal/profile/user/[username]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "profile", "user", "[username]"],
    category: undefined
  },
  {
    path: "/internal/view/free/[username]/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "free", "[username]", "[shortname]"],
    category: undefined
  },
  {
    path: "/internal/view/org/[orgSlug]/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "org", "[orgSlug]", "[shortname]"],
    category: undefined
  },
  {
    path: "/internal/view/pro/[shortname]",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: true,
    segments: ["internal", "view", "pro", "[shortname]"],
    category: undefined
  },
  {
    path: "/",
    isPage: false,
    isLayout: true,
    isApi: false,
    isDynamic: false,
    segments: [],
    category: undefined
  },
  {
    path: "/",
    isPage: true,
    isLayout: false,
    isApi: false,
    isDynamic: false,
    segments: [],
    category: undefined
  }
] as const;

/**
 * Combined forbidden names: static routes + template forbidden names
 */
export const forbiddenNames = [
  "admin",
  "anonymous",
  "api",
  "api/2well2know/oauth-authorization-server",
  "api/2well2know/oauth-authorization-server.hide.",
  "api/2well2know/oauth-protected-resource",
  "api/2well2know/oauth-protected-resource.hide.",
  "api/2well2know/vercel/flags",
  "api/og/imagegen",
  "api/uploadthing",
  "app",
  "assets",
  "auth",
  "blog",
  "cdn",
  "cert",
  "create",
  "deck",
  "decks",
  "demo",
  "docs",
  "edit",
  "email",
  "example",
  "ftp",
  "guest",
  "help",
  "home",
  "index",
  "internal",
  "internal/hero/B2B",
  "internal/hero/B2C",
  "internal/home/user",
  "key",
  "login",
  "logout",
  "mail",
  "manage",
  "mobile",
  "null",
  "oauth",
  "presentation",
  "presentations",
  "pricing",
  "privacy",
  "private",
  "profile",
  "public",
  "register",
  "root",
  "secret",
  "secure",
  "shop",
  "sign-in",
  "sign-up",
  "signin",
  "signup",
  "site",
  "slide",
  "slides",
  "ssl",
  "sso",
  "static",
  "store",
  "support",
  "system",
  "terms",
  "test",
  "undefined",
  "user",
  "waitlist",
  "web",
  "www"
];


/**
 * Routes in the (legal) category
 */
export const legalRoutes = [
  "/privacy",
  "/terms"
] as const;

/**
 * Route matcher for legal routes
 */
export const isLegalRoute = createRouteMatcher([
  "^/privacy$",
  "^/terms$"
]);

/**
 * Routes in the (auth) category
 */
export const authRoutes = [
  "/pricing",
  "/profile/[[...user-profile]]",
  "/sign-in",
  "/sign-up/[[...sign-up]]",
  "/waitlist"
] as const;

/**
 * Route matcher for auth routes
 */
export const isAuthRoute = createRouteMatcher([
  "^/pricing$",
  "^/profile(?:/.*)?$",
  "^/sign-in$",
  "^/sign-up(?:/.*)?$",
  "^/waitlist$"
]);


/**
 * Bypass matcher - instantly passes through middleware
 */
export const isBypass = createRouteMatcher(BYPASS_ROUTES.map(route => 
  route.includes('*') ? route.replace('*', '(.*)') : route
));

/**
 * Dynamic route matchers that use FIRST_SEGMENTS for intelligent routing
 */
export const isProPresentation = createRouteMatcher(["/!([^/]+)"]);

export const isUserProfile = createRouteMatcher([
  "^/(?!" + FIRST_SEGMENTS.join("|") + ")([^/!]+)$"
]);

export const isFreePresentation = createRouteMatcher([
  "^/(?!" + FIRST_SEGMENTS.join("|") + ")([^/!]+)/([^/]+)$"
]);

// Legacy matchers for backwards compatibility
export const isPaidPresentation = isProPresentation;
export const isFreeTier = isFreePresentation;
export const isOrgPresentation = isUserProfile;
