/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationDemoRouteImport } from './routes/presentation.demo'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationDemoRoute = PresentationDemoRouteImport.update({
  id: '/presentation/demo',
  path: '/presentation/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/presentation/demo': typeof PresentationDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/presentation/demo': typeof PresentationDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/presentation/demo': typeof PresentationDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impressum/' | '/presentation/demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/impressum' | '/presentation/demo'
  id: '__root__' | '/' | '/impressum/' | '/presentation/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  PresentationDemoRoute: typeof PresentationDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation/demo': {
      id: '/presentation/demo'
      path: '/presentation/demo'
      fullPath: '/presentation/demo'
      preLoaderRoute: typeof PresentationDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  PresentationDemoRoute: PresentationDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
